### ISSUE TITLE
selenium error

### ISSUE THREAD

**Issue by TommieNL** [JasperMC/docker-MarktplaatsScraper#1]
Hi JasperMC,

I'm planning to use your awesome MarktplaatsScraper.

I'm trying to get it to start with your docker deploy. But I'm getting the error below. Do I miss something?

```
marktplaatsscraper_1  | [services.d] starting services
marktplaatsscraper_1  | [services.d] done.
marktplaatsscraper_1  | Traceback (most recent call last):
marktplaatsscraper_1  |   File "/config/Main.py", line 2, in <module>
marktplaatsscraper_1  |     from Scraper import Scraper
marktplaatsscraper_1  |   File "/config/Scraper.py", line 3, in <module>
marktplaatsscraper_1  |     from selenium import webdriver
marktplaatsscraper_1  | ModuleNotFoundError: No module named 'selenium'
marktplaatsscraper_1  | [cont-finish.d] executing container finish scripts...
marktplaatsscraper_1  | [cont-finish.d] done.
marktplaatsscraper_1  | [s6-finish] waiting for services.
marktplaatsscraper_1  | [s6-finish] sending all processes the TERM signal.
marktplaatsscraper_1  | [s6-finish] sending all processes the KILL signal and exiting.
```

Greets

**Comment by JasperMC** [comment]
Hi Tommie!

It seems I left the pip3 install selenium command commented out in one of the scripts. Can you try cloning the repository again? It might work now. Will check on my end as well

**Comment by JasperMC** [comment]
Just pulled it again and everything seems to be working! I've also merged another user's pull request that adds the required docker files to the main repository. Feel free to use whichever :)

**Comment by TommieNL** [comment]
Hi Jasper, thnx for the quick reply! I'll try this tomorrow on my docker host

**Comment by TommieNL** [comment]
Alright! That works, now on to configuring it ;) Many thanks!

**Comment by JasperMC** [comment]
Good to hear! Let me know if there's anything I can help with. Must admit I didn't expect people to pick this project up and try it out, so maybe there are some gotcha's here and there

**Comment by TommieNL** [comment]
Well I was thinking about building something like this for a while now. And I stumbled on your solution! 

And yeah I have some questions.. probably Pushover related... should i make a new issue on the JasperMC/MarktplaatsScraper repo? Or what works best for you?

**Comment by JasperMC** [comment]
If you could start one on JasperMC/MarktplaatScraper that would be great. Now that we have a docker setup in there as well this repository may have become a bit obsolete.

See you there!

**Comment by TommieNL** [comment]
Ok will, this issue can set to solved then 👍
